services:
  postgres:
    image: postgres:16-alpine
    container_name: nextpick-postgres
    environment:
      POSTGRES_DB: nextpick
      POSTGRES_USER: nextpick_user
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    volumes:
      - nextpick-pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  nextpick-pgdata:
